name = "ubiquity-os-telegram-bridge"
main = "src/worker.ts"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]

[env.dev]
[env.prod]

[observability]
enabled = true

[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"