name: "Workflow Functions"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"

jobs:
  compute:
    name: "Telegram-Bot"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
      BOT_WEBHOOK: ${{ secrets.BOT_WEBHOOK }}
      BOT_WEBHOOK_SECRET: ${{ secrets.BOT_WEBHOOK_SECRET }}

      TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: install dependencies
        run: yarn

      - name: execute directive
        run: npx tsx ./src/workflow-entry.ts
        id: telegram-bot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
          BOT_WEBHOOK: ${{ secrets.BOT_WEBHOOK }}
          BOT_WEBHOOK_SECRET: ${{ secrets.BOT_WEBHOOK_SECRET }}

          TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
