name: "Workflow Functions"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "Signature to identify the Kernel"
      command:
        description: "Command"

jobs:
  compute:
    name: "Kernel-Telegram"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      TELEGRAM_BOT_ENV: ${{ secrets.TELEGRAM_BOT_ENV }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      VOYAGEAI_API_KEY: ${{ secrets.VOYAGEAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      TEMP_SAFE_PAT: ${{ secrets.TEMP_SAFE_PAT }}
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: execute directive
        uses: ./
        env:
          TELEGRAM_BOT_ENV: ${{ secrets.TELEGRAM_BOT_ENV }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          VOYAGEAI_API_KEY: ${{ secrets.VOYAGEAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TEMP_SAFE_PAT: ${{ secrets.TEMP_SAFE_PAT }}
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
